# Default values for django-ledger-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: runtesting/django-ledger
  pullPolicy: Always
  tag: "1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


serviceAccount:

  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: ClusterIP
  port: 8000


ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"


livenessProbe:
  httpGet:
    path: /health/
    port: 8000
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /health/
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volumes:
  - name: django-static-storage
    persistentVolumeClaim:
      claimName: django-static-pvc


volumeMounts:
  - name: django-static-storage
    mountPath: /data/static

nodeSelector: {}

tolerations: []

affinity: {}

envFrom:
  - configMapRef:
      name: django-app-config
  - secretRef:
      name: django-app-secret
