apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-static-pv
  namespace: test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/django-static" 