apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-static-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi 